Complete e2e processing

diff --git a/qsub b/qsub
--- a/qsub
+++ b/qsub
@@ -2,6 +2,11 @@
 
 NS=${PKEBS_NS:-pkebs}
 
+opt_N=""
+opt_p=""
+opt_u=""
+opt_c=""
+
 errr() {
 	local message=$1
 
@@ -11,6 +16,7 @@ errr() {
 
 usage() {
 	echo "Usage: qsub PAYLOAD"
+	# FIXME Options
 	exit 1
 }
 
@@ -18,31 +24,62 @@ submit_job() {
 	local src=$1
 	local dst=$2
  	local bytes=$(stat -c %s $src)
+	local options=""
+
+	[ -z "$opt_N" ] || options="-N $opt_N"
+	[ -z "$opt_p" ] || options="$options -p $opt_p"
+	[ -z "$opt_u" ] || options="$options -u $opt_u"
+	[ -z "$opt_c" ] || options="$options -c $opt_c"
 
 	# NATS message payload by default is up to 1 MB
 	[ 1000000 -lt $bytes ] && errr "File $src is too large: $bytes bytes"
 
 	kubectl -n $NS cp $src dispatcher:${dst} || errr "File transfer failed"
-	# FIXME -N
-	kubectl -n $NS exec -it dispatcher -- /usr/src/app/dispatcher.py $dst || errr "Dispatch failed"
+	kubectl -n $NS exec -it dispatcher -- /usr/src/app/dispatcher.py $options $dst || errr "Dispatch failed"
+	unlink $src
 }
 
 qsub() {
 	local src=$1
-	local dst=$(mktemp -u -t qsub-XXXXXXXXXX)
+	local dst="$(mktemp -u -t qsub-XXXXXXXXXX).zip"
 
 	if [ -f "$src" ] ; then
-		submit_job $src $dst
+		[ -x "$src" ] || errr "File $src is not executable"
+		zip -j -9 -q $dst $src || errr "Creating zip file failed"
+		opt_c=$(basename $src)
 	elif [ -d "$src" ] ; then
 		local runfile=${src}/run.sh
 		[ -f $runfile ] || errr "File $runfile not found"
-		dst=${dst}.zip
 		( cd $src && zip -9 -q -r $dst . ) || errr "Creating zip file failed"
-		submit_job $dst $dst
 	else
 		errr "Unsupported payload type: $src"
 	fi
+
+	submit_job $dst $dst
 }
+
+while getopts "hN:p:u:" opt; do
+    case $opt in
+        h)
+            usage
+            ;;
+        N)
+            opt_N=$(echo $OPTARG | sed -e 's:[^A-Za-z0-9._\-]::g')
+            ;;
+        p)
+            opt_p=$(echo $OPTARG | sed -e 's:[^A-Za-z0-9._/\-]::g' -e 's:^/::' -e 's:/$::')
+            ;;
+        u)
+            opt_u=$(echo $OPTARG | sed -e 's:[^A-Za-z0-9._/\-]::g')
+            ;;
+        \?)
+            echo "Invalid option: -$OPTARG" >&2
+            usage
+            ;;
+    esac
+done
+
+shift $((OPTIND-1))
 
 [ 1 -ne $# ] && usage
 
